### ISSUE TITLE
Allow uploading

### ISSUE THREAD

**Issue by catskull** [catskull/GB-Logo-Generator#19] opened 2016-07-31 02:39 UTC
Allow uploading of a rom  to edit it's header.

Upload a rom.

Populate the fields based on the header information.

Remove the load button from the logo and replace it with a fix button that will reset the logo to the nintendo one.

If they've drawn a new logo warn them that the rom will not boot.

**Comment by catskull** [comment] 2016-08-05 16:43
This rom. If I change the name, download it, then re-upload, the cartridge type and rom size change.

[Rocket Man (Demo) v1.0.gb.zip](https://github.com/catskull/GB-Logo-Generator/files/404204/Rocket.Man.Demo.v1.0.gb.zip)

**Comment by electr0sheep** [comment] 2016-08-05 18:16
This, and other things were fixed in the latest commit: e13c34d6299a8a95836c3c9d7789a562b55907c0

The problem is the ASCII character 00h which is the null character (but yet still a character). I changed the manufacturer and the new lisencee code to show NULL and NA when this occurs. However, there may be other issues regarding this 00h charcter.

**Closed as completed** 2016-08-05 18:18 UTC
